import localFont from "next/font/local";
import "../globals.css";
import {Inter} from "next/font/google"

const inter = Inter({
  weight: ['300','400','500','600'],
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body
        className={`${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
